import { NextPage } from 'next';
import Head from 'next/head';
import Hero from '@/components/Hero';
import BenefitSection from '@/components/BenefitSection';
import AboutUs from '@/components/AboutUs';
import Course from '@/components/Course';
import Testimonies from '@/components/Testimonies';
import FaqSection from '@/components/FaqSection';
import LoginSection from '@/components/LoginSection';
import BlogSection from '@/components/BlogSection';
import FooterSection from '@/components/FooterSection';

const Index: NextPage = () => {
  return (
    <>
      <Head>
        <title>[EDUFREE] - App</title>
        <meta name="description" content="Generated by Create Next Stack." />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main>
        <Hero />
        <BenefitSection />
        <AboutUs />
        <Course />
        <Testimonies />
        <FaqSection />
        <LoginSection />
        <BlogSection />
        <FooterSection />
      </main>
    </>
  );
};

export default Index;
